In [ ]:
import numpy as np

np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

- Boolean Operators

In [ ]:
True and True

True

In [ ]:
True or False

True

In [ ]:
not True

False

In [ ]:
not False

True

In [ ]:
bmi > 21

array([ True, False,  True,  True,  True])

In [ ]:
bmi > 21 and bmi < 22

ValueError: ignored

In [ ]:
np.logical_and(bmi > 21 , bmi < 22)

array([ True, False,  True, False,  True])

In [ ]:
bmi[np.logical_and(bmi > 21 , bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

- Conditional Statements

In [ ]:
z  = 4

if z % 2 == 0: #True
  print("z is even") 

z is even


In [ ]:
z  = 4

if z % 2 == 0: #True
  print("checking " + str(z))
  print("z is even") 

checking 4
z is even


In [ ]:
z  = 5

if z % 2 == 0: #False
  print("checking " + str(z))
  print("z is even") 

In [ ]:
z  = 5

if z % 2 == 0: #False
  print("z is even")
else:
  print("z is odd")

z is odd


In [ ]:
z  = 3

if z % 2 == 0: #False
  print("z is divisible by 2") #False
elif z % 3 == 0:
  print("z is divisible by 3") #True
else:
  print("z is neither divisible by 2 nor by 3")

z is divisible by 3


**Filtering pandas DataFrames**

In [ ]:
import pandas as pd

brics = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DATACAMP/01. Data Scientist with Python/00.DATABASES/brics.csv", index_col = 0)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

**Goal**

- Select countries with area over 8 million km2
- 3 steps:

> 
    Select the area column

> 


    Do comparison on area column

> 


    Use result to select countries

> 



In [ ]:
brics.loc[:,"area"]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
brics.iloc[:,2]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
brics.iloc[:,2] > 8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
is_huge = brics.iloc[:,2] > 8

In [ ]:
is_huge

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
brics[is_huge]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [ ]:
brics[brics["area"] > 8]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [ ]:
np.logical_and(brics["area"]> 8, brics["area"] < 10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
brics[np.logical_and(brics["area"]> 8, brics["area"] < 10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0