In [1]:
import pandas as pd
import numpy as np

In [3]:
amir_deals = pd.read_csv("datasets/amir_deals.csv",index_col=0)
amir_deals.head()

product   client status   amount  num_users
1  Product F  Current    Won  7389.52         19
2  Product C      New    Won  4493.01         43
3  Product B      New    Won  5738.09         87
4  Product I  Current    Won  2591.24         83
5  Product E  Current    Won  6622.97         17

In [4]:
# Sampling from a DataFrame

amir_deals.sample()

product   client status  amount  num_users
125  Product C  Current    Won  482.01         65

In [5]:
amir_deals.sample()

product   client status   amount  num_users
62  Product D  Current    Won  6733.62         27

In [6]:
#Setting a random seed
np.random.seed(10)
amir_deals.sample()

product client status   amount  num_users
70  Product J    New   Lost  3182.09          2

In [7]:
np.random.seed(10)
amir_deals.sample()

product client status   amount  num_users
70  Product J    New   Lost  3182.09          2

In [10]:
#Sampling without replacement

amir_deals.sample(2)

product   client status   amount  num_users
160  Product B  Current    Won  1676.09         29
141  Product B  Current   Lost  5856.18         45

In [11]:
#Sampling with/without replacement
amir_deals.sample(5,replace=True)

product   client status   amount  num_users
72   Product A  Current    Won  5945.63         55
9    Product F  Current    Won  6780.85         80
60   Product E  Current   Lost  6407.69          6
134  Product D  Current    Won  5992.86         98
123  Product B  Current    Won  7219.99         16

In [12]:
#Uniform distribution in python

from scipy.stats import uniform

uniform.cdf(7,0,12)

0.5833333333333334

In [13]:
#Greater than probabilities

1 - uniform.cdf(7,0,12)

0.41666666666666663

In [14]:
uniform.cdf(7,0,12) - uniform.cdf(4,0,12)

0.25000000000000006

In [15]:
#Generating random numbers according to uniform distribution

uniform.rvs(0,5,size=10)

array([4.29935593, 0.57606011, 1.69344235, 2.6612009 , 3.39174779,
       0.52597035, 3.77641816, 2.78460548, 2.585722  , 1.90435231])

In [25]:
# Min and max wait times for back-up that happens every 30 min
min_time = 0
max_time = 30

# Import uniform from scipy.stats
from scipy.stats import uniform

# Calculate probability of waiting less than 5 mins
prob_less_than_5 = uniform.cdf(5,0,30)
print(prob_less_than_5)

0.16666666666666666


In [26]:
# Calculate probability of waiting more than 5 mins
prob_greater_than_5 = 1 - uniform.cdf(5,0,30)
print(prob_greater_than_5)

0.8333333333333334


In [27]:
# Calculate probability of waiting 10-20 mins
prob_between_10_and_20 = uniform.cdf(20,0,30) - uniform.cdf(10,0,30) 
print(prob_between_10_and_20)

0.3333333333333333


## binomial distribution
> binorm.rvs(# of coins, probability of heads/sucess, size= #of trials)

> `1` = head, `0` = tails

In [17]:
from scipy.stats import binom

binom.rvs(1,0.5, size=1)

array([1])

In [18]:
#one flip many times
binom.rvs(1,0.5, size=8)

array([1, 0, 0, 1, 1, 1, 0, 0])

In [19]:
#many flips one time
#flip 8 coins with 50% chance of sucess 1 time
binom.rvs(8,0.5, size=1)

array([2])

In [20]:
binom.rvs(3,0.25, size=10)

array([0, 1, 2, 0, 0, 1, 1, 0, 0, 0])

In [21]:
#What's the probability of 7 heads?
# binom.pmf(num heads, num trials, prob of heads)
#P(heads=7)
binom.pmf(7,10,0.5)

0.11718749999999999

In [22]:
#P(heads <=7)
binom.cdf(7,10,0.5)

0.9453125

In [23]:
#P(heads > 7)
1 - binom.cdf(7,10,0.5)

0.0546875

In [24]:
# Count the deals for each product
counts = amir_deals['product'].value_counts()

# Calculate probability of picking a deal with each product
probs = counts/counts.sum()
print(probs)

Product B    0.348315
Product D    0.224719
Product A    0.129213
Product C    0.084270
Product F    0.061798
Product H    0.044944
Product I    0.039326
Product E    0.028090
Product N    0.016854
Product G    0.011236
Product J    0.011236
Name: product, dtype: float64
